# .github/labeler.yml

version: v1

labels:
  - label: "feat"
    sync: true # remove label if match failed, default: false (pull_request/issue only)
    matcher:
      # Matcher will match on any 8 matchers
      title: "^feat:.*"
      body: "/feat"
      comment: "/feat"
      branch: "^feat/.*"
      baseBranch: "^feat/.*"
      commits: "^feat:.*"
      author:
        - github-actions
        - fuxingloh
      files:
        any: [ "app/*" ]
        all: [ "!app/config/**" ]
        count:
          gte: 1
          lte: 1000

# Optional, if you want labels to generate a success/failure status check
checks:
  - context: "Status Check"
    url: "https://go.to/detail"
    description:
      success: "Ready for review & merge."
      failure: "Missing labels for release."
    labels:
      any:
        - any
        - have
      all:
        - all
        - must
        - have
