version: v1

labels:
  - label: "feat"
    matcher:
      title: "^feat: .*"
      commits: "^feat: .*"

  - label: "fix"
    matcher:
      title: "^fix: .*"
      commits: "^fix: .*"

  - label: "chore"
    matcher:
      title: "^chore: .*"
      commits: "^chore: .*"

  - label: "docs"
    matcher:
      title: "^docs: .*"
      commits: "^docs: .*"

checks:
  - context: "Semantic Pull Request"
    url: "https://github.com/fuxingloh/multi-labeler/blob/main/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - feat
        - fix
        - chore
        - docs
