name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed
  $CHANGES

  ---

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

change-template: |
  <details open>
  <summary>$TITLE @$AUTHOR (#$NUMBER)</summary>

  $BODY
  </details>

include-labels:
  - 'o.x.x'
  - 'x.o.x'
  - 'x.x.o'
  - 'x.x.x'

categories:
  - title: 'Major update o.x.x'
    labels:
      - 'o.x.x'

  - title: 'Minor update x.o.x'
    labels:
      - 'x.o.x'

  - title: 'Patch update x.x.o'
    labels:
      - 'x.x.o'

  - title: 'Other update x.x.x'
    labels:
      - 'x.x.x'

version-resolver:
  major:
    labels:
      - 'o.x.x'
  minor:
    labels:
      - 'x.o.x'
  patch:
    labels:
      - 'x.x.o'
