on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        if: github.actor != 'dependabot[bot]'
        run: echo "Hello World!"

      - name: my-step1
        run: echo "Hello World!"
