on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v32

      - name: comment
        uses: actions-ecosystem/action-create-comment@v1

        run: echo '${{ toJSON(steps.changed-files-specific.outputs) }}'

        with:
          github_token: ${{ secrets.github_token }}
          body: |
            @${{ github.actor }}
