on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    # if: github.event.label.name == 'o.x.x'
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        run: echo "Hello World!"

      - name: my-step1
        run: echo "Hello World!"
